name: Auto approve

on:
  workflow_dispatch:
    inputs:
      pullRequestNumber:
        description: Pull request number to auto-approve
        required: true
  pull_request_target:

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{secrets.TANISHIKING_GH_TOKEN_FOR_TEST}}
          pull-request-number: ${{ github.event.inputs.pullRequestNumber }}
