name: Auto approve

on:
  pull_request_target:
    types: [labeled]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v2
        if: contains(github.event.pull_request.labels.*.name, 'automerge') && github.actor == 'tanishiking'
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
