name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: temurin
      - uses: sbt/setup-sbt@v1
      - run: sbt "ci"
